### ISSUE TITLE
minor Bug: Victory Road strength tiles light up if clock indicates it is night time

### ISSUE THREAD

**Issue by DaniRainbow** [danenders/pokeclassic#100]
On the white tiles where you are supposed to push boulders on with Strength, they will glow like a beacon if it is night time in the game. The Victory Road cave does not change brightness or require Flash to see, so I believe this is minor bug. The tiles work as intended whether or not they are lighting up.

**Comment by danenders** [comment]
I'll take a look at the palettes, but if this doesn't prevent progress I'm not going to fix. My lighting branch is too out of date to merge w/o headaches.
