### ISSUE TITLE
Bug: Rival AI battle items

### ISSUE THREAD

**Issue by DaniRainbow** [danenders/pokeclassic#101]
The Rival will only have access to Potions throughout the entire game. Even when you rechallenge them in the Viridian Gym they can only use Potions. Because Potions provide insignificant HP in the late game, the Rival AI will use a Potion immediately if their pokemon are barely damaged. This allows the player to get more "free" hits on the Rival's pokemon as the 20 HP does not make a difference in most cases.

Adjusting the Rival AI to have better healing items as the game progresses would mean they are a more appropriate challenge to the player and that they heal at the intended HP.

**Comment by danenders** [comment]
Updated the Rival's items. These were still using placeholders.
