### ISSUE TITLE
Bug: Silph Co "Lapras NPC" changes sides during post game content

### ISSUE THREAD

**Issue by DaniRainbow** [danenders/pokeclassic#102]
The NPC in Silph Co that gives the player a Lapras upon the first visit becomes a Rocket member to fight in a double battle during the second Team Rocket infiltration of Silph Co. After you defeat them, this NPC gets the original dialogue they had after giving the player the Lapras.

**Comment by danenders** [comment]
Added a flag to this NPC; he should disappear if you've return to the room after he's given you Lapras. The postgame rocket shared a space with him.
