### ISSUE TITLE
Bug: PokeGear Arnold

### ISSUE THREAD

**Issue by DaniRainbow** [danenders/pokeclassic#105]
Route 21 "Arnold" is missing the type of trainer and name but has the rechallenge pokesquare. Calling them has jumbled text.
Strongly think this is related to #96

**Comment by danenders** [comment]
Doesn't appear to be an issue for me.
![Screen Shot 2023-08-13 at 8 09 24 AM](https://github.com/danenders/pokeclassic/assets/65201358/7cf57860-745b-4a15-8b8b-96b9e5472d48)

**Comment by danenders** [comment]
I did fix that text cutoff though.

**Comment by DaniRainbow** [comment]
When I do my next playthrough to test I'll make sure I am recording or have
things set up to get screenshots. I'm testing on actual hardware and with a
newer version of mGBA than I saw in your screenshot. Thanks for taking the
time to respond to all these issues I found.

**Comment by DaniRainbow** [comment]
Associated with #96 and still not fixed, sorry to report.

Here's some screenshots! https://imgur.com/a/3tjwaxK
