### ISSUE TITLE
enhancement: Scott's mailbox has no interaction or text

### ISSUE THREAD

**Issue by DaniRainbow** [danenders/pokeclassic#109]
Scott's mailbox outside his house does not say "Scott's House" like it would for the player or Rival house. 

Suggestion: Make interactable (if this is not a minor bug) to say "Scott's House" or something of that nature.

**Comment by danenders** [comment]
Not a bug, just didn't think people noticed that stuff. Added for immersion :)

**Comment by DaniRainbow** [comment]
Lol sorry I came through with all my observations but I was excited when I discovered this ROM hack and checked everything I could think of when I did a big search. Thanks!
