### ISSUE TITLE
Bug: Team Rocket at Nugget Bridge won't take "no" as an answer

### ISSUE THREAD

**Issue by DaniRainbow** [danenders/pokeclassic#113]
If you tell Team Rocket no to the secret prize, Looker will appear and take the member away. If you walk back to Cerulean on the right side of the bridge, you will trigger the "you won!" message with a ghost. They will appear as a team rocket representative and then won't talk to you more while the text box becomes unresponsive. If you walk down the middle of the bridge you can escape. Walking back on the right retriggers this event with a ghost. Saying yes will see the event go to Jessie and James, then end properly. Walking back through on the right side will no longer trigger if you said yes at any point to the secret prize.

Encounter needs a little work so it can end even when saying no

**Comment by danenders** [comment]
The bonus encounter for Jessie/James, aka the Secret Prize, was the only route setting the variable that disabled the triggers. If you say "no" and battle the standard rocket, it now also sets the variable, so it should prevent this from reoccurring.
