### ISSUE TITLE
enhancement: elevator access in Rocket Hideout

### ISSUE THREAD

**Issue by DaniRainbow** [danenders/pokeclassic#119]
If a player doesn't take the elevator to B1F before fighting Giovanni, the gate blocking the elevator will never remove because the "are you lost, little mouse?" Grunt that will unlock after being defeated is not there after defeating Giovanni. I suggest adding some other trigger to that gate to unlock it when Team Rocket is no longer around.

**Comment by danenders** [comment]
Added a check on transition for the flag that hides the celadon rockets. If you finish the hideout without fighting the Grunt, this should remove the barrier.
