### ISSUE TITLE
Bug: Giovanni sprite doesn't appear, lady that lets you rest will thank you prematurely

### ISSUE THREAD

**Issue by DaniRainbow** [danenders/pokeclassic#120]
After defeating Jessie and James in Silph Co, the lady in Silph Co that allows you to rest will no longer let you rest and will thank the player for saving Silph Co. Giovanni has not been defeated by this point. When you go into the President room, Giovanni speaks to the player but his sprite is not viewable.

**Comment by DaniRainbow** [comment]
This appears to effect all of Silph Co and Saffron. I whiteout to Giovanni and all of Team Rocket is gone from Saffron.

**Comment by danenders** [comment]
I think this is because Jessie & James use the same "hide" flag that the saffron rockets do. When you 'remove object', I think it also sets their flag, so it was prematurely hiding all rockets. I've given them a separate flag.
