### ISSUE TITLE
Bug: can't rechallenge Gym Leader Giovanni

### ISSUE THREAD

**Issue by DaniRainbow** [danenders/pokeclassic#122]
After beating Giovanni in his gym, you can talk to him again and he will talk about challenging you but it skips the fight, he basically says he needs to go away, and then you can immediately pick up the Macho Brace where he stood.

**Comment by MrMazzone** [comment]
I wondering this is how it should be, since once your champion you can challenge the rival at the gym.

**Comment by DaniRainbow** [comment]
Absolutely right, after the Pokemon League Giovanni is gone and you fight
your Rival. It's just if you talk to Gym Leader Giovanni after beating him
once, he has different dialogue as if you haven't seen him for a while,
seems to challenge you, doesn't challenge you, acts defeated, disappears
and leaves behind the Macho Brace. I may be interpreting the series of
events wrong but it looks like it's missing a fight.

**Comment by danenders** [comment]
I'll review the dialogue to make sure it's not misleading, but this isn't a bug.

Giovanni cannot be re-challenged, I just added some post battle dialogue in case the player talks to them again before leaving the gym. If you leave and come back, he's gone, but if you talk to him I wanted to give the Giovanni "arc" an ending without him just disappearing.

**Comment by DaniRainbow** [comment]
I think the title of this bug should be changed to Giovanni's gym text is out of order. I included a couple of screenshots and a link to his dialogue from Fire Red/ Leaf Green to show what I mean.

To summarize, he appears to start talking to you about half way through his intro dialogue, you win, you get the badge and TM, and then he begins to do the beginning part of his introduction followed by the latter half of his defeat dialogue.

https://imgur.com/a/X73e4Y8

https://bulbapedia.bulbagarden.net/wiki/Giovanni/Quotes#Pok.C3.A9mon_FireRed_and_LeafGreen
