### ISSUE TITLE
Bug: pre-Victory Road Rival fight has no dialogue, starts fight the moment Rival walks on screen

### ISSUE THREAD

**Issue by DaniRainbow** [danenders/pokeclassic#123]

**Comment by danenders** [comment]
I think this should be fixed. Script didn't have a 'wait movement' after the rival walk was triggered. Let me know if this is still happening.

**Comment by DaniRainbow** [comment]
He's using battle items appropriately now (that Jolteon got hands, wow) but his intro dialogue is still broken. The battle starts as he is walking towards you.

https://imgur.com/a/khlLNjR
