### ISSUE TITLE
Bug: Celadon city is broken after commits made on 7/29/23

### ISSUE THREAD

**Issue by DaniRainbow** [danenders/pokeclassic#125]
This one has the largest impact on the game that I've seen so far.

If you have all 151 Pokemon and Fly to Celadon you will land and not be able to move from that spot. If you enter Celadon from Saffron, the game slows down and says you have 190 coins then teleports you into the wall of Seafoam/Seafloor Caverns (can't remember exactly, I need to get this on video). You can't fly out of there but you can Dig. It made me appear in the bottom corner under the guard checkpoint in Saffron. Walking back to Celadon had the screen go brighter and the game froze. I'm going to see what happens if you enter Celadon from Cycling Road.

If allowed, I can post a link to my save so others can test

**Comment by DaniRainbow** [comment]
Update: it's not just the Pokedex being completed that causes these issues, it happens any time entering Celadon now. Entered on a new save and the issue happened.

**Comment by DaniRainbow** [comment]
![Uploading IMG_20230730_140421.jpg…]()

**Comment by DaniRainbow** [comment]
![IMG_20230730_140421](https://github.com/danenders/pokeclassic/assets/96923698/48a6a5f7-1ebe-4bc9-8977-5f324da18f24)

**Comment by DaniRainbow** [comment]
Commit 1902a1b appears to be the culprit

**Comment by danenders** [comment]
> 

That's absolutely the cause; wasn't paying attention to where I added the flag! Will fix tonight!

**Comment by DaniRainbow** [comment]
Thanks @danenders, I was going to put a pull request in but my fork needs some cleanup before I do another one. 😅

**Comment by danenders** [comment]
Fixed!
