### ISSUE TITLE
Bug: Cedar dialogue at Professor Oak post Championship

### ISSUE THREAD

**Issue by DaniRainbow** [danenders/pokeclassic#136]
Please see screenshots in provided link, this is what Cedar says after you defeat the Champion and return to Professor Oak's lab.

https://imgur.com/a/RUIsAoS

**Comment by danenders** [comment]
What, you don't speak glitch-ish? :P

I probably forgot to close a line somewhere in her dialogue, should be an easy fix.

I'm wrapping up a gamejam project so I'll probably do another sit down with this in a few days and knock out a bunch of fixes for v1.4 just like we did for 1.3, so keep 'em coming!

**Comment by DaniRainbow** [comment]
You got it!
