### ISSUE TITLE
Team rocket question

### ISSUE THREAD

**Issue by PokeGunk** [danenders/pokeclassic#142]
Are Jessie/James in this like original Yellow? So far this looks like most complete GBA Yellow remake unless I am mistaken.  Also any more updates coming to address recent submitted bugs?

**Comment by danenders** [comment]
Yes to both. Jessie and James have plenty of screen time and also have a few additional optional encounters that may or may not occur based on the order you do things/the answers you give.

Some bug fixes and possibly new content will come eventually, but I'm updating this slower now as I work on other projects. Please continue to submit bugs, as other users sometimes investigate, and when I come back to make fixes I try to do a lot at once.

**Comment by PokeGunk** [comment]
Cool, don't care for new content as long as it's a complete pokemon yellow game.  The perks of the emerald features are a plus.  Don't care about custom content or additional pokemon generations.  Bugs and glitches getting fixed are my biggest priority.   There is not one working yellow GBA rom anywhere they are all either incomplete or full of bugs. I'll keep an eye out on the next big update.  Thanks!

Note: I will be playing this on GPI Case 2w with Recalbox if that matters.
