### ISSUE TITLE
How to catch Mew

### ISSUE THREAD

**Issue by Mte90** [danenders/pokeclassic#162]
Reading on internet I can't find so much information if in this rom it is possible.

On a reddit comment for this ROMHack it was mentioned under the truck like the old metropolitan story. http://new.reddit.com/r/PokemonROMhacks/comments/13znynh/comment/jmueoxk/?utm_source=reddit&utm_medium=web2x&context=3

Someone has suggestions how to get it? As this is a modded version of Pret I am not sure if the usual way with Pokemon Emerald works.

**Comment by Mte90** [comment]
So checking the code that part is true https://github.com/danenders/pokeclassic/blob/9c3a49affcb9b9f5e67dd9ae6a5e079af3bf26b5/data/maps/SSAnne_Exterior/scripts.inc#L76

Reading the code is not clear how to execute it and on internet also how to reach that truck.

Also the wiki doesn't mention where find Mew https://github.com/danenders/pokeclassic/wiki/Pok%C3%A9mon-Locations

**Comment by JimmyForman** [comment]
I found this explanation on reddit. The truck is just a hint. You need to find the "Old Sea Map" and it tells you the island to surf to.

**Comment by Mte90** [comment]
Where you can find that map?

**Comment by JimmyForman** [comment]
I'm having a hard time finding the post i saw that explained it. It was from a user on reddit.

**Comment by MrMazzone** [comment]
From what I remember, there is no way to catch Mew. Just the easter egg with the truck.

**Comment by danenders** [comment]
Mew is obtainable. Get the map off the wall in the basement of Cinnabar Mansion, then bring it to the ship captain.

**Comment by Mte90** [comment]
But if the SS Anne already left what I can do?

**Comment by Mte90** [comment]
So I was able to find the old man and get the map to go the farewell islands and has nothing to do with ss anne.
