### ISSUE TITLE
Bug: Unable to use fly

### ISSUE THREAD

**Issue by danenders** [danenders/pokeclassic#46]
Reddit user reported FLY doesn't work at all.

**Comment by MrMazzone** [comment]
Fly works for me. But I cannot fly to most locations. Example Indigo Plateau and Cinnabar Island, even though I have been there and used Poke Center.

**Comment by danenders** [comment]
This is fixed in the next release. Thank you Dani96sp/MrMazzone/DaniRainbow, you were all correct and it was the flags not being set.

**Comment by DaniRainbow** [comment]
Sorry to resurrect this one, but Fuchsia City is not able to be flown to. Noticed this when I was heading to catch Articuno. This was after all 8 badges. Could fly everywhere else, even with Cinnabar being black dot.

https://imgur.com/a/rTwzWhQ
