### ISSUE TITLE
Bug: Saffron Elevators

### ISSUE THREAD

**Issue by danenders** [danenders/pokeclassic#56]
User reported possible bug with Saffron elevators.

**Comment by DaniRainbow** [comment]
In Silph Co, the elevator in the ground level will only let you choose a floor between the highest and 9. The text is broken for the Floors and Info boxes.

**Comment by danenders** [comment]
Emerald elevator scripts are garbage. There were some legit errors in my script, so now the elevator works. But creating a multichoice that scrolls for 11 floors is more trouble than its worth; i've replaced the buttons with a 2 column layout. The only thing that's lost with this solution is your cursor doesn't start at the current floor, which is not a big deal.

**Comment by DaniRainbow** [comment]
I'm sorry to report but the elevators still don't work as intended. The interface is fixed and looks so much better, but the elevator warps take you to the wrong rooms. For example, entering the elevator on 2F in Silph Co. will  have your character walk in through the main entrance to Silph Co. on 1F. 

In my own testing when trying to change how a script works in other places of the game on my fork, I found that room warps would get horrendously messed up even without changing those specifically. I wonder if correcting the events reported in #120  caused the warps of Silph Co. to have issues.
