### ISSUE TITLE
Cycling Road grass bug

### ISSUE THREAD

**Issue by ttdevmode93** [danenders/pokeclassic#64]
No wild Pokémon are encountered in the grass on cycling road. Due to this, Eevee and other Pokémon that are supposed to appear there are currently unobtainable.

**Comment by MrMazzone** [comment]
This one just bummed me out. This is Route 17 is the only spot you can catch Eevee. Can't finish the dex without Eevee and the Eeveelutions.

Also, If you surf on Route 17 when you go back on land you are walking and not on bike.

**Comment by ttdevmode93** [comment]
Yeah, I'm only 5 Pokémon away from finishing my dex and I can't get them because they are all bugged at the moment.

**Comment by MrMazzone** [comment]
@ttdevmode93 I am trying a fix and just submitted a PR. If you know how to compile the ROM from the source, try out my fix. I am looking at how to compile from source now.

**Comment by ttdevmode93** [comment]
I will have to wait for a patch, unfortunately

**Comment by MrMazzone** [comment]
@ttdevmode93 I created a patch with my fix for the Route 17 grass and the visited locations bug preventing fly to some locations (#46 )

https://drive.google.com/file/d/1lDhv_rXoqmrEteChgFREgyCKZSuoqOIf/view?usp=sharing

Tested it out and all seems great! I got an Eevee! This is my first time building these, so you may want to back up your saves before playing with my patch.

**Comment by danenders** [comment]
This is fixed for next release
