### ISSUE TITLE
Bug: Mewtwo & Zapdos don't disappear after being caught

### ISSUE THREAD

**Issue by ttdevmode93** [danenders/pokeclassic#65]
It seems like in some cases, the legendary Pokémon don't vanish after they are caught by the player. This allows them to be caught again.

**Comment by MrMazzone** [comment]
This is a feature, not a bug! 🙂

**Comment by MrMazzone** [comment]
I just played through these parts and can confirm the same.

**Comment by DaniRainbow** [comment]
Articuno does not have this issue, so I pulled up the scripts.inc for the PowerPlant and SeafoamIslands_B4F. They are very similar but I did find a difference between the two. 

From SeafoamIslands_B4F/scripts.inc : 

SeafoamIslands_B4F_OnTransition::
	call_if_set FLAG_CAUGHT_ARTICUNO, SeafoamIslands_B4F_EventScript_HideArticuno
	call_if_unset FLAG_CAUGHT_ARTICUNO, SeafoamIslands_B4F_EventScript_TryShowArticuno
	call_if_unset FLAG_STOPPED_SEAFOAM_B4F_CURRENT, SeafoamIslands_B4F_EventScript_CheckStoppedCurrent
	call_if_set FLAG_STOPPED_SEAFOAM_B4F_CURRENT, SeafoamIslands_B4F_EventScript_SetNoCurrentLayout
	end

From PowerPlant/scripts.inc : 

PowerPlant_OnTransition:
	setvar VAR_TEMP_1, 0
	setvar VAR_TEMP_2, 0
	call_if_unset FLAG_DEFEATED_POWER_PLANT_ELECTRODE_1, PowerPlant_EventScript_ShowElectrode1
	call_if_unset FLAG_DEFEATED_POWER_PLANT_ELECTRODE_2, PowerPlant_EventScript_ShowElectrode2
	call_if_set FLAG_CAUGHT_ZAPDOS, PowerPlant_EventScript_HideZapdos
	call_if_unset FLAG_CAUGHT_ZAPDOS, PowerPlant_EventScript_TryShowZapdos
	end

I do not have a save file where Articuno was not caught or defeated yet to test, but I want to try removing the setvar for VAR_TEMP_1 and VAR_TEMP_2.  They aren't mentioned anywhere else in the file, but may be needed for the Electrode encounters that happen with the fake items. Anyone willing to test these changes or provide me with a save where I can access Zapdos without much hassle?

**Comment by DaniRainbow** [comment]
In addition, I pulled up the scripts for Mewtwo's encounter and it also showed only one colon. 

From CeruleanCave_B1F/scripts.inc

CeruleanCave_OnTransition:
	call_if_set FLAG_CAUGHT_MEWTWO, CeruleanCave_EventScript_HideMewtwo
	call_if_unset FLAG_CAUGHT_MEWTWO, CeruleanCave_EventScript_TryShowMewtwo
	end

**Comment by DaniRainbow** [comment]
Adding the : back didn't fix the Zapdos encounter. Still investigating

**Comment by danenders** [comment]
Issues with the MapScripts. Cerulean Cave had two sets of MapScripts being initialized, so I cleared one out, which should fix Mewtwo. Power Plant was attempting to fire  both "OnTransition" and "OnResume" on RESUME, likely due to a copy+paste mistake. Should fix both Zapdos and Electrodes in the Power Plant.

**Comment by DaniRainbow** [comment]
Fixed! Bravo https://imgur.com/a/dtVZUzr
