### ISSUE TITLE
Bug: cannot talk to Bill after second Pokemon League attempt

### ISSUE THREAD

**Issue by DaniRainbow** [danenders/pokeclassic#72]
You wake up in your house after defeating Professor Oak and your mom says you have a visitor, so you go downstairs to talk to Bill but Bill has no dialogue. If you try to leave the home your mother won't let you cause you ignored Bill. You cannot escape the house using methods like Teleport, Dig, or Escape Rope. This is a soft lock.

**Comment by DaniRainbow** [comment]
Opening up the map in porymap revealed Bills object did not have any scripts attached to him. Attached the "PlayersHouse_1F_EventScript_Bill" script to him and you can now get the item he provides as well as leave the house. This fixes the soft lock. Will make a pull request shortly.

**Comment by danenders** [comment]
Corrected for next release.
