### ISSUE TITLE
enhancement: add Route 10/ Rock Tunnel as a Fly destination

### ISSUE THREAD

**Issue by DaniRainbow** [danenders/pokeclassic#73]
Pokemon Yellow would not allow you to Fly to Route 10/ Rock Tunnel but Pokemon FireRed/ LeafGreen had that as a feature. While it would be deviating from Pokemon Yellow, I think it's a quality of life improvement worth making.

**Comment by danenders** [comment]
With the current bugs for Fly, I'm going to avoid adding new Fly spots. There's not much reason to return to Rock Tunnel / Route 10 after clearing and going to the Power Plant, so I don't think it detracts too much.

If we solve all the Fly bugs maybe I'll add that in a future update.
