### ISSUE TITLE
minor Bug: Trainer Tip in Viridian Forest does not apply to Pokemon Classic

### ISSUE THREAD

**Issue by DaniRainbow** [danenders/pokeclassic#76]
A sign on the east side of Viridian Forest indicates that players can have Professor Oak can evaluate their pokedex at a PC in the Pokemon Center. This feature is not in Pokemon Classic and is instead accessible using the PokeGear Call function by making a call to Professor Oak. 

Suggested fix: update sign to describe suggest getting Professor Oak's number for pokedex evaluations.

Alternative fix: enable the feature on Pokemon Center PCs from the vanilla game to give players more options.

**Comment by danenders** [comment]
Good call! Going to change it to talk about the Cell Phone.
