### ISSUE TITLE
enhancement: change Lavender Town sign information to something other than Silph Scope

### ISSUE THREAD

**Issue by DaniRainbow** [danenders/pokeclassic#86]
Pokemon Classic removes the Silph Scope from the game and is not needed to make progression in the Pokemon Tower. A sign outside of the Pokemon Tower talks about the Silph Scope, hinting for players to find it so they can identify the unseen. 

I recommend removing the sign entirely or replacing the text to something related to Lavender Town and/or the Pokemon Tower.

**Comment by danenders** [comment]
Fixed in another issue.
