### ISSUE TITLE
Bug: trainer in Pokemon Tower that gives TM42 gifts it multiple time and the dialogue loops without closing

### ISSUE THREAD

**Issue by DaniRainbow** [danenders/pokeclassic#87]
In the first floor of the Pokemon Tower, Nuffle's Trainer (bald trainer at the north of the room not there in vanilla Pokemon Yellow) gives TM42 and when that happens all other NPCS begin to move. The prompt for receiving the TM does not wait for the "A" prompt. Hitting "A" doesn't close the speech box. Pressing "A" again makes him repeat his gift. If you try to walk away after getting it you can but the text will remain. Speaking to other people or accessing your Start menu will jumble up the text. Clears when leaving the room by going upstairs or exiting the Pokemon Tower all together.

**Comment by danenders** [comment]
Fixed!
