### ISSUE TITLE
enhancement: Pokemon Tower NPC overhaul

### ISSUE THREAD

**Issue by DaniRainbow** [danenders/pokeclassic#88]
There is lots of dialogue in the Pokemon Tower that talks about the Silph Scope. Pokemon Classic does not have the Silph Scope in it and as such, NPCs no longer need to provide the player hints about getting the Silph Scope before continuing.

I suggest changing the text to provide hints that are applicable to Pokemon Classic.

**Comment by danenders** [comment]
Removed some references to the silph scope. Replaced the sign with a trainer tip for the PokeNav, too.
