### ISSUE TITLE
Bug: grumpy Game Corner patron doesn't give coins, dialogue loops

### ISSUE THREAD

**Issue by DaniRainbow** [danenders/pokeclassic#89]
In the Rocket Game Corner, the cranky guy in the bottom right that is supposed to give the player coins and tell them to "shoo" does not give coins and his dialogue loops. The player has to leave the Game Corner while the dialogue box is up to get rid of the message. Considering a bug instead of minor bug because this currency giver does not work as intended.

**Comment by danenders** [comment]
Should be fixed.
