### ISSUE TITLE
Bug: Koga's dialogue cuts off during rematch

### ISSUE THREAD

**Issue by DaniRainbow** [danenders/pokeclassic#92]
In the Fuchsia City Gym, Koga's dialogue cuts off while talking to the character about a rematch. The part that cuts off says "utter de" and I'm assuming it means utter destruction. I do now know if there are other words after that are missing. Prevents the player from experiencing the full Gym leader banter before a battle.

**Comment by danenders** [comment]
haha wow this one's really a mess. It's "utter defeat" but "utter destruction" was a nice guess :P  (I kinda like it more!)
I reworked the dialogue, this is fixed.
