### ISSUE TITLE
Bug: inaccurate room warps in Safari Zone

### ISSUE THREAD

**Issue by DaniRainbow** [danenders/pokeclassic#93]
In the area of the Safari Zone where you find the Gold Teeth and the competition building to acquire Surf and daily Rare Candies, leaving the area by the north exit does not work properly. If you leave on the left side it will warp you to the entrance of the competition building. If you leave on the right side it will take you to the intended Safari Zone area north of that place. Does not prevent progression but can impact the amount of steps a player has to make, ultimately prematurely ending the Safari Zone experience.

**Comment by danenders** [comment]
Fixed!

**Comment by DaniRainbow** [comment]
I love to see it. Thanks for your efforts!
