### ISSUE TITLE
Bug: Route 21 Juggler Elite (?)

### ISSUE THREAD

**Issue by DaniRainbow** [danenders/pokeclassic#96]
While Surfing to Cinnabar Island, you will encounter a male Juggler/ Elite trainer on an islet and their whole interaction logic is not working as intended. The text box gets garbled immediately and the sprite that shows during a battle is that of a hiker instead of the Juggler. He then throws out a black circle with a ? in the middle (icon to show no pokemon data is found attached to that event) and your pokemon defeats it in one hit. You are awarded 1 exp and then met with a garbled message with "no more balls" being the only legible text. The battle ends and this trainer may or may not give you their number. 

This trainer is not present in Pokemon Yellow.

**Comment by danenders** [comment]
https://github.com/danenders/pokeclassic/assets/65201358/3435a764-53dd-47db-ba74-4d9cfa83aa19

Didn't appear to be an issue.

**Comment by DaniRainbow** [comment]
Still an issue, it was for a different trainer than the one in your recording.

Here's some screenshots! https://imgur.com/a/mDfXXiw

**Comment by Sanicle87** [comment]
Issue is still present (build 1.3).

I actually reset back to my previous save, this reminded me way too much of MissingNo. Not risking any save corruption from this trainer. Especially since when he gives you his phone number, it glitches the phone because his name's not a valid entry.

**Comment by DaniRainbow** [comment]
> Issue is still present (build 1.3).
> 
> I actually reset back to my previous save, this reminded me way too much of MissingNo. Not risking any save corruption from this trainer. Especially since when he gives you his phone number, it glitches the phone because his name's not a valid entry.

What a menace. I think you did the right thing reverting your save even though it never corrupted  my save.
