### ISSUE TITLE
minor Bug: Cinnabar Island Research Center scientist logic

### ISSUE THREAD

**Issue by DaniRainbow** [danenders/pokeclassic#99]
When the scientist that resurrects fossils gives the player a revived Aerodatcyl, the scientist will start to move around. I did not notice this with the revival of Kabuto or Omanyte. It is unclear if this has the chance to hinder player progression or retrieval of the pokemon.

**Comment by danenders** [comment]
Hmm. I think this is because he had a 'wander' movement type, and him not moving in others may have been a coincidence? That shouldn't be the case anyway, so I changed them to a static movement type. Should be fixed.
